language: python
python:
  - "3.6.5"
before_install:
  - sudo apt-get install unixodbc unixodbc-dev
services:
  - mysql
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install mycli==1.19.0
  - pip install coverage
  - pip install codecov
before_script:
  - mysql -e "CREATE DATABASE archery CHARSET UTF8;"
  - python manage.py makemigrations
  - python manage.py makemigrations sql
script:
  - coverage run manage.py test -v 3

after_success:
  - codecov
