language: python
python:
  - "3.4"
  - "3.6.5"
services:
  - mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e "CREATE DATABASE archer_master CHARSET UTF8;"
  - python manage.py makemigrations sql
script:
  - python manage.py test sql -v 3
